import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@app/ConvexClientProvider";

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwBeTSbKcvuLQQsvGnVzGK2D_a4-ypPGA&libraries=visualization"
        ></script>
      </head>
      <body className={lora.className}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
